Fix Installer crash when requesting file list
Options in `info.options` are already of `Option` type, not
`InstallerOption`, hence the `option._object` call fails with e.g.:

```
  File "/home/lahvuun/git/cemm/cemm_venv/lib/python3.6/site-packages/pyfomod/installer.py", line 257, in files
    for info in self._previous_pages
  File "/home/lahvuun/git/cemm/cemm_venv/lib/python3.6/site-packages/pyfomod/installer.py", line 259, in <listcomp>
    for file_info in FileInfo.process_files(option._object.files, self.path)
AttributeError: 'Option' object has no attribute '_object'
```

Probably a leftover from a local revision.