Fix Installer crash when testing flag conditions
Options in info.options are already of `Option` type, not
`InstallerOption`, hence the `option._object` call fails with e.g.:

```
  File "/home/lahvuun/git/cemm/cemm_venv/lib/python3.6/site-packages/pyfomod/installer.py", line 284, in flags
    for info in self._previous_pages
  File "/home/lahvuun/git/cemm/cemm_venv/lib/python3.6/site-packages/pyfomod/installer.py", line 285, in <listcomp>
    for option in info.options
AttributeError: 'Option' object has no attribute '_object'
```

Probably a leftover from a local revision.